services:
  helloworld:
    container_name: helloworld
    image: crccheck/hello-world
    ports:
      - 8000
  
  langchain:
    build: ./services/langchain
    volumes:
      - ./services/langchain/:/usr/src/
    ports:
      - 8501:8501

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./services/certbot/conf:/etc/letsencrypt
      - ./services/certbot/www:/var/www/certbot
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./services/certbot/conf:/etc/letsencrypt
      - ./services/certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email "connectingsteven@gmail.com" -d "testing-the-langchain.de" --agree-tos